project:
  type: website

website:
  title: "Spatial Analysis of EPC Data"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - EPCSpatialAnalysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

